"""Metadata for merit_ledger. Generated by metametameta — do not edit by hand."""

__all__ = [
    "__title__",
    "__version__",
    "__description__",
    "__readme__",
    "__credits__",
    "__keywords__",
    "__license__",
    "__requires_python__",
    "__status__",
]

__title__ = "merit_ledger"
__version__ = "0.1.0"
__description__ = "Keep track of your merit. A Chinese Mahayana Buddhist practice from 1000 years ago."
__readme__ = "README.md"
__credits__ = [{"name": "Matthew Dean Martin", "email": "matthewdeanmartin@gmail.com"}]
__keywords__ = ["merit_ledger"]
__license__ = "MIT"
__requires_python__ = ">=3.10"
__status__ = "3 - Alpha"
